name: CI on Xamarin Android Project

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Show Current Directory
        run: ls
      
      - name: Andorid
        run: |
          nuget restore FlensaApp.sln
          cd FlensaApp
          cd Flensa.Android
          msbuild FlensaApp.Android.csproj /verbosity:normal /t:PackageForAndroid /p:Configuration=Debug
