name: CI on Xamarin Android Project

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'
     
      - name: Install Dependencies
        run: nuget restore FlensaApp.sln
      
      - name: Build
        run: |
          cd FlensaApp
          cd Flensa.Android
          msbuild FlensaApp.Android.csproj /verbosity:normal /t:PackageForAndroid /p:Configuration=Debug
